#!/bin/sh

if [ $# -lt 1 ]; then
    echo "Usage: where program"
    exit 1
fi

PROG=$(type -p $1)

FILE=${PROG:-$1}

if [ -e "$FILE" ]; then
    echo -n $FILE
    if [ -L "$FILE" ]; then
	echo -n " -> "
	readlink -en $FILE
    fi
    echo
fi
